### ISSUE TITLE
Confirmation dialog is displayed multiple times if one module requires user confirmation

### ISSUE THREAD

**Issue by gfabrego** [googlecodelabs/android-dynamic-features#2]
**Steps to reproduce**

1. Add some resources to a module so it's bigger than 10MB and requires user confirmation in order to be installed
2. Do a fresh install from the Play Store.
3. Open the app
4. Click on "Install all features now"

**Result**

The confirmation dialog to install new modules is shown four times, one for each module. This is because it's iterating over module names when state is "confirmation required"

**Expectation**

Dialog should be shown only once

**Comment by pfmaggi** [comment]
Thanks for reporting this.
We have verified the problem and fixed with commit 1b81133c32b93bc2cd0a3fc6ea3982c12258211a 

There's now [an additional step](https://codelabs.developers.google.com/codelabs/on-demand-dynamic-delivery/#10) in the codelab that showcase this case.

Again: Thanks for helping improving the code and the codelab!
