### ISSUE TITLE
APK from app bundle does not contain the dynamic module requested

### ISSUE THREAD

**Issue by wisechengyi** [googlecodelabs/android-dynamic-features#3]
Chatted with Ibrahim, and was asked to file an issue.

Repro: https://github.com/wisechengyi/android-dynamic-features/tree/yicdn

<img width="1183" alt="screen shot 2019-02-07 at 2 57 40 pm" src="https://user-images.githubusercontent.com/596358/52448445-be009800-2ae8-11e9-8c41-3c090ccc5ee7.png">

Click 'show assets' once app launches, and it will show 'error loading assets', whereas it should a textbox titled 'Asset Content'. When stepping through https://github.com/wisechengyi/android-dynamic-features/blob/yicdn/app/src/main/java/com/google/android/samples/dynamicfeatures/MainActivity.kt#L56, `manager.installedModules` is empty.

If switching from 'APK from app bundle' to 'Default APK', it works.

**Comment by wisechengyi** [comment]
FWIW, dynamic delivery works by deploying the aab to play console, so likely a local toolchain issue.

**Comment by pfmaggi** [comment]
I've filed a bug internally and I'm waiting for a reply to update this issue.  
To test locally from the App Bundle, you can use [bundletool](https://github.com/google/bundletool).

In particular, once you've generated the App Bundle, you can use the following commands to install the right minimum set for your app:

``` sh
bundletool build-apks --bundle app.aab --output app.apks
features/app/build/outputs/bundle/debug$ bundletool install-apks --apks app.apks
```

Keep in mind that this is not going to be able to download the additional modules. To test the download, at this moment, you've to go through Play.

Or you can install the complete application (universal APK) using the commands:

``` sh
bundletool build-apks --mode=universal --bundle app.aab --output app.apks
features/app/build/outputs/bundle/debug$ bundletool install-apks --apks app.apks
```

More information on how to use Bundletool can be find on the [documentation site](https://developer.android.com/studio/command-line/bundletool).

**Comment by pfmaggi** [comment]
I was supposing that this was now fixed in the newer AS, but seems that it's still a problem.

Closing this and follow up on the [public issue](https://issuetracker.google.com/144146956).

**Comment by ziSo12** [comment]
Encountering a similar error. When using the above build configuration (APK from app bundle), my build fails with the error message:
`The APK Set archive does not contain the following modules: [list of my dynamic feature modules]`

I'm also getting a warning:
`The option setting 'android.injected.modules.install.list=list of my dynamic feature modules' is experimental.`

All I could find is that this error message is from the bundletool source code, which means that AS is using bundletool during the build process. 
Do I need some special option and use bundletool manually in order to fix this?

I'm getting an "acces denied" message when trying to view your "public issue" link.
